name: Build, test and deploy to sandbox

on:
  pull_request:
  push:
    branches:
      - main

env:
  TEST_URL: test.com

jobs:
  build_and_test:
    name: Build and test azure login
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST}}
